# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewer', '0002_book_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='books',
        ),
    ]
