# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewer', '0003_auto_20170925_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='books',
            new_name='users',
        ),
    ]
