# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewer', '0005_auto_20170926_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='users',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ManyToManyField(related_name='user_reviews', to='BeltReviewer.User'),
        ),
    ]
