# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewer', '0006_auto_20170926_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
    ]
