# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewer', '0007_auto_20170926_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='users',
        ),
    ]
